### ISSUE TITLE
Username exploit

### ISSUE THREAD

**Issue by NoMoreZombies** [GregHib/void#548]
**Describe the bug**
You can sign in to any account with any password if you change any of the characters in the username field to uppercase characters.

**To Reproduce**
1. Try to sign in to an existing account using an invalid password and uppercase characters in the username.

**Expected behavior**
You shouldn't be able to sign in to an existing account with any password by using uppercase or lowercase characters in the username field.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 22H2

**Comment by GregHib** [comment]
Thanks for the bug report, this was a critical oversight and has been fixed in #551.

The cause was windows' file system treating all files as case-insensitive where the login server was case-sensitive; this allowed the account to load from file like normal despite the password check believing it's a new account logging in for the first time.

Now the server is also case-insensitive so will work as expected, and should the incorrect state occur again (e.g. a players file manually modified while the server is running) it'll now show the client an account disabled message.
